---
title: "Project Team Bear"
formatt: html
---

# Welcome

Welcome to the Project Team Bear website. This site hosts our data project deliverables, visualizations, and short write-ups produced by each team member.

## The Project

This project is designed for students, researchers, policymakers, and community members who are interested in understanding how race and ethnicity shape experiences with police traffic stops. By presenting clear, interactive visualizations, our goal is to make the data accessible to non-technical audiences while still providing enough depth to support evidence-based discussions about equity, bias, and policing practices in the United States. 

### Dataset
Our analysis uses traffic stop data from the Stanford Open Policing Project (SOPP), available [here](https://openpolicing.stanford.edu/data/). It is a large-scale initiative that compiles millions of stop records obtained through public records requests to law enforcement agencies nationwide. The SOPP dataset provides standardized variables such as driver demographics, stop reason, search details, contraband findings, and stop outcomes (e.g., warnings, citations, arrests).

For this project, we focus on the city of Charlotte, North Carolina for the years 2005 and 2015 . As the full dataset is too large for Altair’s rendering limits (nearly 4 million observations from 2000–2015), our group worked with either curated subsets or random samples appropriate for each exploratory analysis. The specific fields we used vary across team members but include age, race, action taken, search intrusiveness, contraband type, and stop outcomes.

A quick navigation to each team member's page:

<div class="d-flex flex-wrap">
  <a href="alex.qmd" class="btn btn-primary btn-lg m-2">Temporal</a>
  <a href="brianna.qmd" class="btn btn-secondary btn-lg m-2">Race and Ethnicity</a>
  <a href="eddie.qmd" class="btn btn-success btn-lg m-2">Sex and Age</a>
  <a href="roxanna.qmd" class="btn btn-info btn-lg m-2">Outcomes</a>
</div>


#### **Intended Audience**
Anyone interested in how race and ethnicity shape experiences with traffic stops including students, researchers, and policymakers. This project helps reveal where differences in treatment appear, such as during searches or arrests. Ultimately, by using data and presenting our insights clearly, we aim to encourage discussions about equity, accountability, and bias in law enforcement practices.

## About the team

#### **Members:**
* Edward Sobczak: I'm majoring in Microbiology & Immunology and minoring in Data Science, and I enjoy crocheting!
* Alex Haddon: I study Economics and Data Science and I love to ski ⛷️
* Brianna Chau: I am a third year Economics student, with a minor in Data Science. I am interested in strength training, cardio, and watching my macros!
* Roxanna Ng: I am majoring in Political Science and minoring in Data Science, and I enjoy exploring good restaurants!
